name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Develop APK
        run: ./gradlew assembleDevelopRelease

      - name: Build Production APK
        run: ./gradlew assembleProductionRelease

      - name: Run Unit Tests
        run: ./gradlew testDevelopDebugUnitTest

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDevelopDebugUnitTest/

      - name: Upload Develop APK
        uses: actions/upload-artifact@v3
        with:
          name: develop-apk
          path: app/build/outputs/apk/develop/release/app-dev-release.apk

      - name: Upload Production APK
        uses: actions/upload-artifact@v3
        with:
          name: production-apk
          path: app/build/outputs/apk/production/release/app-prod-release.apk