name: CI - Develop

on:
  push:
    branches: [ "main" ] # Branch Develop

jobs:
  build-dev:
    name: Build Dev APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Dev APK
        run: ./gradlew assembleDevRelease

      - name: Run Unit Tests
        run: ./gradlew testDevDebugUnitTest