name: CI - Develop Branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build Dev APK
        run: ./gradlew assembleDevRelease