name: CI - Production Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Prod APK
        run: ./gradlew assembleProdRelease

      - name: Run Unit Tests
        run: ./gradlew testDevDebugUnitTest

#      - name: Upload Unit Test Reports
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: unit-test-report
#          path: app/build/reports/tests/testDevDebugUnitTest/

#      - name: Upload Dev APK
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: dev-apk
#          path: app/build/outputs/apk/dev/release/app-dev-release.apk

#      - name: Upload Prod APK
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: prod-apk
#          path: app/build/outputs/apk/prod/release/app-prod-release.apk